#version 450

#include "gsplat_radix_sort_include.glsl"

layout(local_size_x = 128) in;

shared uint sharedHistogram[16]; // 16 bins * 128 threads

void main() {
    /* This shader computes local histograms of the number of elements in each bin
     * which are then written into a consective array in global memory.
     * The shader following on this histogram creation will then perform a
     * prefix sum to compute the offsets for each bin for the final sorting pass,
     * i.e., the placement of each element in the sorted array while preserving
     * the original order of elements in the same bin.
     */

    uint binIdx = gl_LocalInvocationIndex.x;

    if (binIdx < 16) {
        sharedHistogram[binIdx] = 0;
    }

    barrier(); 

    uint itemsPerWorkGroup0 = pushConstants.numElements / gl_NumWorkGroups.x;
    uint iterationsPerWorkGroup = (itemsPerWorkGroup0 + gl_WorkGroupSize.x - 1) / gl_WorkGroupSize.x;
    uint itemsPerWorkGroup = iterationsPerWorkGroup * gl_WorkGroupSize.x;
    
    //uint itemsPerWorkGroup = (pushConstants.numElements + gl_NumWorkGroups.x - 1) / gl_NumWorkGroups.x;
    uint idx = gl_WorkGroupID.x * itemsPerWorkGroup + gl_LocalInvocationID.x;
    uint endIdx = idx + itemsPerWorkGroup;
    while ((idx < endIdx) && (idx < pushConstants.numElements)) {
        uint value;
        uint index;
        if (pushConstants.pass % 2 == 0) {
            value = radixValuesA[idx];
            index = indexesA[idx];
        } else {
            value = radixValuesB[idx];
            index = indexesB[idx];
        }

        // get the bin of the current value for the current pass
        uint bin = (value >> (pushConstants.pass * 4)) & 0xF;

        // count the occurrences of this bin
        uint last_bin_value = atomicAdd(sharedHistogram[bin], 1);

        // debugPrintfEXT("uadsd value: %u, bin value: %u\n", uadsd, bin);
        // if (gl_LocalInvocationID.x == 127 && gl_WorkGroupID.x == 319) {
        //     debugPrintfEXT("idx: %u endIdx: %u numElements: %u itemsPerWorkGroup: %u\n", idx, endIdx, pushConstants.numElements, itemsPerWorkGroup);
        // }

        idx += gl_WorkGroupSize.x;
    }

    barrier();
    // memoryBarrier();

    // since we walked through the array with idx,
    // now reset it to the invocation id
    // idx = gl_GlobalInvocationID.x;
    // now we need to write the histogram to the global memory
    if (binIdx < 16) {
        uint globalBinIdx = gl_NumWorkGroups.x * binIdx + gl_WorkGroupID.x;
        inputBuffer3.histogram[globalBinIdx] = sharedHistogram[binIdx];
    }

    if (gl_LocalInvocationID.x == 0) {
        if (gl_WorkGroupID.x == 0) {
            offsetBuffer.offsets[gl_WorkGroupID.x] = 0;
        } else {
            offsetBuffer.offsets[gl_WorkGroupID.x] = -1;
        }
    }

}