// SPDX-FileCopyrightText: Dirk Fortmeier
//
// SPDX-License-Identifier: MIT

#version 450

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;
layout(push_constant) uniform PushConstants {
    uint batch;
    uint channels;
    uint inputHeight;
    uint inputWidth;
    uint outputHeight;
    uint outputWidth;
} pc;
layout(set = 0, binding = 0) restrict readonly buffer InputBuffer { float inputData[]; };
layout(set = 0, binding = 1) restrict readonly buffer ScalesBuffer { float scales[]; };
layout(set = 0, binding = 2) restrict writeonly buffer OutputBuffer { float outputData[]; };

void main() {
    uint index = gl_GlobalInvocationID.x;
    uint total = pc.batch * pc.channels * pc.outputHeight * pc.outputWidth;
    if (index >= total) return;
    uint x = index % pc.outputWidth;
    uint value = index / pc.outputWidth;
    uint y = value % pc.outputHeight;
    value /= pc.outputHeight;
    uint channel = value % pc.channels;
    uint batch = value / pc.channels;
    uint inputX = min(x * pc.inputWidth / pc.outputWidth, pc.inputWidth - 1);
    uint inputY = min(y * pc.inputHeight / pc.outputHeight, pc.inputHeight - 1);
    uint inputIndex = ((batch * pc.channels + channel) * pc.inputHeight + inputY) * pc.inputWidth + inputX;
    outputData[index] = inputData[inputIndex];
}
