#version 450

#extension GL_EXT_debug_printf : enable

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) readonly buffer InputBufferA {
    mat4 A[ ];
};

layout(set = 0, binding = 1) readonly buffer InputBufferB {
    vec4 B[ ];
};

layout(set = 0, binding = 2) buffer OutputBufferR {
    vec4 R[ ];
};


void main()
{
    uint index = gl_GlobalInvocationID.x;
    R[index] = A[index] * B[index];
}