#version 450

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) readonly buffer InputBufferA {
    float A[ ];
};

layout(set = 0, binding = 2) buffer OutputBufferR {
    float R[ ];
};

layout(set = 1, binding = 0) uniform UniformBufferObject {
    float multiplier;
};

#extension GL_EXT_debug_printf : enable

void main()
{
    uint index = gl_GlobalInvocationID.x;
    R[index] = A[index] * multiplier;

}