# SPDX-FileCopyrightText: Dirk Fortmeier
#
# SPDX-License-Identifier: MIT

"""Writes src/unicode_categories.inc: code point ranges of the Unicode general
categories L (letters), M (marks) and N (numbers), which the GGUF tokenizer's
pre-tokenizer distinguishes. Data: Python's unicodedata module.

Usage (from this directory): uv run python make_unicode_tables.py
"""

from __future__ import annotations

import sys
import unicodedata
from pathlib import Path

OUTPUT = Path(__file__).resolve().parents[2] / "src" / "unicode_categories.inc"


def main() -> None:
    ranges = []  # (first, last, class letter)
    for code in range(sys.maxunicode + 1):
        major = unicodedata.category(chr(code))[0]
        if major not in "LMN":
            continue
        if ranges and ranges[-1][2] == major and ranges[-1][1] == code - 1:
            ranges[-1] = (ranges[-1][0], code, major)
        else:
            ranges.append((code, code, major))
    lines = [
        # The tags are split so that REUSE does not read them as this script's own.
        "// SPDX" "-FileCopyrightText: Dirk Fortmeier",
        "//",
        "// SPDX" "-License-Identifier: MIT",
        "",
        "// Generated by scripts/qwen_gguf/make_unicode_tables.py from Unicode "
        f"{unicodedata.unidata_version}; do not edit.",
        "// Sorted, non-overlapping code point ranges of the general categories L, M and N.",
    ]
    for first, last, major in ranges:
        lines.append(f"{{0x{first:X}, 0x{last:X}, UnicodeClass::{ {'L': 'Letter', 'M': 'Mark', 'N': 'Number'}[major] }}},")
    OUTPUT.write_text("\n".join(lines) + "\n")
    print(OUTPUT, len(ranges), "ranges")


if __name__ == "__main__":
    main()
